import type { ConfigItem, TableColumn, TableFilter } from "@/modules/shared/types";
import type { ProductionImportByCar, KernelData } from "./productionImportByCarType";

// A utility type to make all properties of an object optional.
type DeepPartial<T> = {
    [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

export const tableHead: TableColumn[] = [
    { columnName: "شناسه", row_id: "id", type: "string" },
    { columnName: "سطح", row_id: "level", type: "number" },
    { columnName: "شهر", row_id: "agriculture.city", type: "string" },
    { columnName: "کشاورزی", row_id: "agriculture.agriculture", type: "string" },
    { columnName: "راننده", row_id: "car.driver", type: "string" },
    { columnName: "خودرو", row_id: "car.car", type: "string" },
    { columnName: "محصول", row_id: "product.product", type: "number" },
    { columnName: "صاحب محصول", row_id: "product.product_owner", type: "number" },
    { columnName: "نوع کشتار", row_id: "slaughter_type", type: "string" },
    { columnName: "نوع سفارش", row_id: "order_type", type: "string" },
    { columnName: "وزن کامل", row_id: "second_step.full_weight", type: "number" },
    { columnName: "تعداد قفس", row_id: "second_step.cage_number", type: "number" },
    { columnName: "وضعیت برنامه‌ریزی", row_id: "is_planned.status", type: "boolean" },
    { columnName: "وضعیت لغو", row_id: "is_cancelled.status", type: "boolean" },
    { columnName: "وضعیت تأیید", row_id: "is_verified.status", type: "boolean" },
    { columnName: "وضعیت سری تولید", row_id: "production_series.status", type: "string" },
];

export function getCreateDialogConfigs({ cities, agricultures, drivers, cars, products, product_owners, slaughter_types, order_types, users, statuses }: KernelData): ConfigItem[] {
    return [
        {
            name: "agriculture.city",
            label: "شهر",
            type: "select-box",
            options: cities,
            defaultValue: cities?.[0]?.value,
            required: true,
        },
        {
            name: "agriculture.agriculture",
            label: "کشاورزی",
            type: "select-box",
            options: agricultures,
            defaultValue: agricultures?.[0]?.value,
            required: true,
        },
        {
            name: "car.driver",
            label: "راننده",
            type: "select-box",
            options: drivers,
            defaultValue: drivers?.[0]?.value,
            required: true,
        },
        {
            name: "car.car",
            label: "خودرو",
            type: "select-box",
            options: cars,
            defaultValue: cars?.[0]?.value,
            required: true,
        },
        {
            name: "product.product",
            label: "محصول",
            type: "select-box",
            options: products,
            defaultValue: products?.[0]?.value,
            required: true,
        },
        {
            name: "product.product_owner",
            label: "صاحب محصول",
            type: "select-box",
            options: product_owners,
            defaultValue: product_owners?.[0]?.value,
            required: true,
        },
        {
            name: "slaughter_type",
            label: "نوع کشتار",
            type: "select-box",
            options: slaughter_types,
            defaultValue: slaughter_types?.[0]?.value || "Slaughterhouse delivery",
            required: true,
        },
        {
            name: "order_type",
            label: "نوع سفارش",
            type: "select-box",
            options: order_types,
            defaultValue: order_types?.[0]?.value || "company",
            required: true,
        },
        {
            name: "production_series.product_owner",
            label: "صاحب محصول سری تولید",
            type: "select-box",
            options: product_owners,
            defaultValue: product_owners?.[0]?.value,
            required: true,
        },
        {
            name: "production_series.create.date",
            label: "تاریخ ایجاد سری تولید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: true,
        },
        {
            name: "production_series.create.user",
            label: "کاربر ایجادکننده سری تولید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: true,
        },
        {
            name: "production_series.start.date",
            label: "تاریخ شروع سری تولید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: true,
        },
        {
            name: "production_series.start.user",
            label: "کاربر شروع‌کننده سری تولید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: true,
        },
        {
            name: "production_series.finish.date",
            label: "تاریخ اتمام سری تولید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: true,
        },
        {
            name: "production_series.finish.user",
            label: "کاربر اتمام‌کننده سری تولید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: true,
        },
        {
            name: "production_series.status",
            label: "وضعیت سری تولید",
            type: "select-box",
            options: statuses,
            defaultValue: statuses?.[0]?.value || "pending",
            required: true,
        },
    ];
}

export function getUpdateDialogConfigs({ cities, agricultures, drivers, cars, products, product_owners, slaughter_types, order_types, users, statuses }: KernelData): ConfigItem[] {
    return [
        {
            name: "level",
            label: "سطح",
            type: "int-input",
            defaultValue: 1,
            required: true,
        },
        {
            name: "agriculture.city",
            label: "شهر",
            type: "select-box",
            options: cities,
            defaultValue: cities?.[0]?.value,
            required: true,
        },
        {
            name: "agriculture.agriculture",
            label: "کشاورزی",
            type: "select-box",
            options: agricultures,
            defaultValue: agricultures?.[0]?.value,
            required: true,
        },
        {
            name: "car.driver",
            label: "راننده",
            type: "select-box",
            options: drivers,
            defaultValue: drivers?.[0]?.value,
            required: true,
        },
        {
            name: "car.car",
            label: "خودرو",
            type: "select-box",
            options: cars,
            defaultValue: cars?.[0]?.value,
            required: true,
        },
        {
            name: "product.product",
            label: "محصول",
            type: "select-box",
            options: products,
            defaultValue: products?.[0]?.value,
            required: true,
        },
        {
            name: "product.product_owner",
            label: "صاحب محصول",
            type: "select-box",
            options: product_owners,
            defaultValue: product_owners?.[0]?.value,
            required: true,
        },
        {
            name: "slaughter_type",
            label: "نوع کشتار",
            type: "select-box",
            options: slaughter_types,
            defaultValue: slaughter_types?.[0]?.value || "Slaughterhouse delivery",
            required: true,
        },
        {
            name: "order_type",
            label: "نوع سفارش",
            type: "select-box",
            options: order_types,
            defaultValue: order_types?.[0]?.value || "company",
            required: true,
        },
        {
            name: "first_step.entrance_to_slaughter.date",
            label: "تاریخ ورود به کشتارگاه",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "first_step.entrance_to_slaughter.user",
            label: "کاربر ورود به کشتارگاه",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "second_step.full_weight",
            label: "وزن کامل",
            type: "int-input",
            defaultValue: 0,
            required: false,
        },
        {
            name: "second_step.source_weight",
            label: "وزن منبع",
            type: "int-input",
            defaultValue: 0,
            required: false,
        },
        {
            name: "second_step.cage_number",
            label: "تعداد قفس",
            type: "int-input",
            defaultValue: 1,
            required: false,
        },
        {
            name: "second_step.product_number_per_cage",
            label: "تعداد محصول در هر قفس",
            type: "int-input",
            defaultValue: 1,
            required: false,
        },
        {
            name: "third_step.start_production.date",
            label: "تاریخ شروع تولید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "third_step.start_production.user",
            label: "کاربر شروع تولید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "fourth_step.finish_production.date",
            label: "تاریخ اتمام تولید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "fourth_step.finish_production.user",
            label: "کاربر اتمام تولید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "fifth_step.empty_weight",
            label: "وزن خالی",
            type: "int-input",
            defaultValue: 0,
            required: false,
        },
        {
            name: "fifth_step.transit_losses_wight",
            label: "وزن تلفات حمل",
            type: "int-input",
            defaultValue: 0,
            required: false,
        },
        {
            name: "fifth_step.transit_losses_number",
            label: "تعداد تلفات حمل",
            type: "int-input",
            defaultValue: 0,
            required: false,
        },
        {
            name: "fifth_step.losses_weight",
            label: "وزن تلفات",
            type: "int-input",
            defaultValue: 0,
            required: false,
        },
        {
            name: "fifth_step.losses_number",
            label: "تعداد تلفات",
            type: "int-input",
            defaultValue: 0,
            required: false,
        },
        {
            name: "fifth_step.fuel",
            label: "سوخت",
            type: "int-input",
            defaultValue: 0,
            required: false,
        },
        {
            name: "fifth_step.extra_description",
            label: "توضیحات اضافی",
            type: "string-input",
            defaultValue: "",
            required: false,
        },
        {
            name: "sixth_step.exit_from_slaughter.date",
            label: "تاریخ خروج از کشتارگاه",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "sixth_step.exit_from_slaughter.user",
            label: "کاربر خروج از کشتارگاه",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "seventh_step.product_slaughter_number",
            label: "تعداد محصول کشتار",
            type: "int-input",
            defaultValue: 1,
            required: false,
        },
        {
            name: "seventh_step.finish.date",
            label: "تاریخ اتمام",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "seventh_step.finish.user",
            label: "کاربر اتمام",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "is_planned.status",
            label: "وضعیت برنامه‌ریزی",
            type: "switch",
            defaultValue: false,
            required: false,
        },
        {
            name: "is_planned.user_date.date",
            label: "تاریخ برنامه‌ریزی",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "is_planned.user_date.user",
            label: "کاربر برنامه‌ریزی",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "is_cancelled.status",
            label: "وضعیت لغو",
            type: "switch",
            defaultValue: false,
            required: false,
        },
        {
            name: "is_cancelled.user_date.date",
            label: "تاریخ لغو",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "is_cancelled.user_date.user",
            label: "کاربر لغو",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "is_verified.status",
            label: "وضعیت تأیید",
            type: "switch",
            defaultValue: false,
            required: false,
        },
        {
            name: "is_verified.user_date.date",
            label: "تاریخ تأیید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "is_verified.user_date.user",
            label: "کاربر تأیید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "create.date",
            label: "تاریخ ایجاد",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: false,
        },
        {
            name: "create.user",
            label: "کاربر ایجادکننده",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: false,
        },
        {
            name: "production_series.product_owner",
            label: "صاحب محصول سری تولید",
            type: "select-box",
            options: product_owners,
            defaultValue: product_owners?.[0]?.value,
            required: true,
        },
        {
            name: "production_series.create.date",
            label: "تاریخ ایجاد سری تولید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: true,
        },
        {
            name: "production_series.create.user",
            label: "کاربر ایجادکننده سری تولید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: true,
        },
        {
            name: "production_series.start.date",
            label: "تاریخ شروع سری تولید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: true,
        },
        {
            name: "production_series.start.user",
            label: "کاربر شروع‌کننده سری تولید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: true,
        },
        {
            name: "production_series.finish.date",
            label: "تاریخ اتمام سری تولید",
            type: "string-input",
            defaultValue: "2025-08-14 10:26",
            required: true,
        },
        {
            name: "production_series.finish.user",
            label: "کاربر اتمام‌کننده سری تولید",
            type: "select-box",
            options: users,
            defaultValue: users?.[0]?.value,
            required: true,
        },
        {
            name: "production_series.status",
            label: "وضعیت سری تولید",
            type: "select-box",
            options: statuses,
            defaultValue: statuses?.[0]?.value || "pending",
            required: true,
        },
    ];
}

export const updateDialogDocs: DeepPartial<ProductionImportByCar> = {
    id: "296",
    level: 1,
    agriculture: {
        city: "",
        agriculture: "",
    },
    car: {
        driver: "",
        car: "",
    },
    product: {
        product: 0,
        product_owner: 0,
    },
    slaughter_type: "Slaughterhouse delivery",
    order_type: "company",
    first_step: {
        entrance_to_slaughter: {
            date: "2025-08-14 10:26",
            user: "",
        },
    },
    second_step: {
        full_weight: 0,
        source_weight: 0,
        cage_number: 1,
        product_number_per_cage: 1,
    },
    third_step: {
        start_production: {
            date: "2025-08-14 10:26",
            user: "",
        },
    },
    fourth_step: {
        finish_production: {
            date: "2025-08-14 10:26",
            user: "",
        },
    },
    fifth_step: {
        empty_weight: 0,
        transit_losses_wight: 0,
        transit_losses_number: 0,
        losses_weight: 0,
        losses_number: 0,
        fuel: 0,
        extra_description: "",
    },
    sixth_step: {
        exit_from_slaughter: {
            date: "2025-08-14 10:26",
            user: "",
        },
    },
    seventh_step: {
        product_slaughter_number: 1,
        finish: {
            date: "2025-08-14 10:26",
            user: "",
        },
    },
    is_planned: {
        status: false,
        user_date: {
            date: "2025-08-14 10:26",
            user: "",
        },
    },
    is_cancelled: {
        status: false,
        user_date: {
            date: "2025-08-14 10:26",
            user: "",
        },
    },
    is_verified: {
        status: false,
        user_date: {
            date: "2025-08-14 10:26",
            user: "",
        },
    },
    create: {
        date: "2025-08-14 10:26",
        user: "",
    },
    production_series: {
        create: {
            date: "2025-08-14 10:26",
            user: "",
        },
        start: {
            date: "2025-08-14 10:26",
            user: "",
        },
        finish: {
            date: "2025-08-14 10:26",
            user: "",
        },
        product_owner: 0,
        status: "pending",
    },
};

export const tableFilter: TableFilter[] = [
    {
        name: "agriculture__city",
        label: "شهر",
        type: "autocomplete",
        options: [], // Populate dynamically from API
        placeholder: "جستجوی شهر",
        defaultValue: "",
    },
    {
        name: "agriculture__agriculture",
        label: "کشاورزی",
        type: "autocomplete",
        options: [], // Populate dynamically from API
        placeholder: "جستجوی کشاورزی",
        defaultValue: "",
    },
    {
        name: "car__driver",
        label: "راننده",
        type: "autocomplete",
        options: [], // Populate dynamically from API
        placeholder: "جستجوی راننده",
        defaultValue: "",
    },
    {
        name: "car__car",
        label: "خودرو",
        type: "autocomplete",
        options: [], // Populate dynamically from API
        placeholder: "جستجوی خودرو",
        defaultValue: "",
    },
    {
        name: "product__product",
        label: "محصول",
        type: "autocomplete",
        options: [], // Populate dynamically from API
        placeholder: "جستجوی محصول",
        defaultValue: "",
    },
    {
        name: "product__product_owner",
        label: "صاحب محصول",
        type: "autocomplete",
        options: [], // Populate dynamically from API
        placeholder: "جستجوی صاحب محصول",
        defaultValue: "",
    },
    {
        name: "slaughter_type",
        label: "نوع کشتار",
        type: "select-box",
        options: [], // Populate dynamically from API
        defaultValue: "Slaughterhouse delivery",
    },
    {
        name: "order_type",
        label: "نوع سفارش",
        type: "select-box",
        options: [], // Populate dynamically from API
        defaultValue: "company",
    },
    {
        name: "second_step__full_weight",
        label: "وزن کامل",
        type: "range",
        min: 0,
        max: 1000,
        step: 1,
        defaultValue: [0, 500],
    },
    {
        name: "second_step__cage_number",
        label: "تعداد قفس",
        type: "range",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: [0, 50],
    },
    {
        name: "is_planned__status",
        label: "وضعیت برنامه‌ریزی",
        type: "boolean",
        defaultValue: false,
    },
    {
        name: "is_cancelled__status",
        label: "وضعیت لغو",
        type: "boolean",
        defaultValue: false,
    },
    {
        name: "is_verified__status",
        label: "وضعیت تأیید",
        type: "boolean",
        defaultValue: false,
    },
    {
        name: "production_series__status",
        label: "وضعیت سری تولید",
        type: "select-box",
        options: [], // Populate dynamically from API
        defaultValue: "pending",
    },
];